version: '3.7'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: memo-game-server
    container_name: memo-game-server
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  mongo:
    image: mongo
    container_name: memo-game-db
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - app-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    image: memo-game-client
    container_name: memo-game-client
    command: yarn run dev
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local