# Pull the Node image from Docker Hub
FROM node:latest

# Setting Working Directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Copying only package.json
COPY package*.json ./

RUN apt-get update

# Install Dependencies
RUN npm install

# Copy rest of the code to container
COPY . .

RUN npm install -g nodemon

EXPOSE 5000

# Run the API on Nodemon
CMD ["nodemon", "server.js"]